# Generated by Django 3.2 on 2022-02-24 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tattooblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tattoopost',
            name='authorofpost',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
