# Generated by Django 3.2 on 2022-02-24 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tattooblog', '0002_tattoopost_authorofpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tattoopost',
            old_name='authorofpost',
            new_name='body',
        ),
    ]
