# Generated by Django 3.2 on 2022-02-24 16:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tattooblog', '0003_rename_authorofpost_tattoopost_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='tattoopost',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dxsodecl1/image/upload/v1644248279/cld-sample.jpg', max_length=255, verbose_name='image'),
        ),
    ]
