# Generated by Django 3.2 on 2022-02-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tattooblog', '0004_tattoopost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tattoopost',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
