# Generated by Django 3.2 on 2022-03-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tattooblog', '0005_alter_tattoopost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tattoopost',
            name='thumb',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
