# Generated by Django 3.2 on 2022-03-01 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tattooblog', '0006_tattoopost_thumb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tattoopost',
            name='thumb',
        ),
    ]
