# Generated by Django 3.2 on 2022-03-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tattooblog', '0008_tattoopost_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tattoopost',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
