# Generated by Django 3.2 on 2022-03-29 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tattooblog', '0009_alter_tattoopost_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tattoopost',
            name='slug',
        ),
        migrations.AddField(
            model_name='tattoopost',
            name='slug_category',
            field=models.SlugField(blank=True, default='', editable=False, max_length=250, null=True),
        ),
    ]
