# Generated by Django 3.2 on 2022-03-29 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tattooblog', '0011_rename_slug_category_tattoopost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tattoopost',
            name='slug',
            field=models.SlugField(blank=True, default='', editable=False, max_length=250, null=True, unique=True),
        ),
    ]
