# Generated by Django 3.2 on 2022-03-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tattooblog', '0012_alter_tattoopost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tattoopost',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
