# Generated by Django 3.2 on 2022-04-20 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tattooblog', '0013_alter_tattoopost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tattoopost',
            name='body',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
