# Generated by Django 3.2 on 2022-04-22 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_profile_image'),
        ('tattooblog', '0014_alter_tattoopost_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tattoopost',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
