# Generated by Django 3.2 on 2022-04-28 23:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tattooblog', '0015_alter_tattoopost_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tattoopost',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dxsodecl1/image/upload/v1648317615/blank_jg5vze.jpg', max_length=255, verbose_name='image'),
        ),
    ]
