# Generated by Django 3.2 on 2022-04-29 00:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dxsodecl1/image/upload/v1648317615/blank_jg5vze.jpg', max_length=255, verbose_name='image'),
        ),
    ]
